install:
  - npm install
  - bower install
script:
  - gulp
after_success:
  - npm install -g firebase-tools
  - firebase --non-interactive deploy --token "${FIREBASE_TOKEN}"
cache:
  directories:
  - node_modules
  - bower_components
